# Generated by Django 3.2.5 on 2021-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210707_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
