# Generated by Django 3.2.5 on 2021-07-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transferhistory_transferlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlist',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_offer', to='app.player'),
        ),
    ]
