# Generated by Django 3.2.5 on 2021-07-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transferlist_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ordinary User'), (2, 'Admin User')], default=1),
        ),
    ]
