# Generated by Django 3.2.5 on 2021-07-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='app.team'),
        ),
    ]
